web:
  image: nginx:latest
  ports: 
    - 8081:80
  volumes: 
    - ./:/app
    - ./default.conf:/etc/nginx/conf.d/default.conf
  links: 
    - php

php:
  image: php:7-fpm
  volumes: 
    - .:/app

db:
  image: postgres
  volumes: 
    - db:/var/lib/postgresql/data
  ports:
    - 5432:5432